### PR TITLE
removed main.go && created library out of project

### PR DESCRIPTION
**Pull request by hosseinmirzapur**
simply removed main.go, and added a new directory named "client" and created a client.go, also included tests for it in the same directory, and moved generator.go inside the client directory

### CODE REVIEW

**Comment by steebchen** [comment]
Can you clarify why this change makes the Go client better? I see the motivation a little bit but don't immediately see any value. Plus, the main problem is that it would break existing as I believe the generate command would be different.

**Comment by hosseinmirzapur** [comment]
> Can you clarify why this change makes the Go client better? I see the motivation a little bit but don't immediately see any value. Plus, the main problem is that it would break existing as I believe the generate command would be different.

I'm aware that removing the main.go may break the code, but the problem is that your repo cannot be used directly as a standalone library due to the main.go file in the root. what if some developer wanted to use this great package as a library to use it in their own framework? can you create a repository with the library form of your package, as i changed it?

**Comment by steebchen** [comment]
I see, can you elaborate on how you want to use it as a library?

**Comment by hosseinmirzapur** [comment]
> I see, can you elaborate on how you want to use it as a library? Feel free to chat on [discord](https://goprisma.org/docs/community) as well.

Thanks, just messaged you

**Comment by steebchen** [comment]
As discussed via DM, it should be possible to use all methods directly even with a main.go in the root folder

**Pull request closed without merging**
