### PR TITLE
feat(errors): add unique constraint violation error

### LINKED ISSUE #213: Provide proper error handling for unique constraints
Apart from ErrNotFound, there are currently no other exported errors. We should export various errors such as unique constraint violations and so on. They should also contain details if possible.

For example, checking for a unique constraint violation could look as follows:

```go
user, err := db.User.CreateOne(...)
if v, ok := prisma.IsUniqueConstraintViolation(err); ok {
  // do something here
  log.Printf("duplicate entry on columns %s", v.Fields)
} else if err != nil {
 // probably nothing we can do here
  return err
}
```

### PR DESCRIPTION
**Pull request by steebchen**
Adds helper functions for one of the most commonly used errors, a unique constraint violation.

Note that different databases return slightly different metadata, which means the implementation details depend on what database you use:

```go
user, err := db.User.CreateOne(...).Exec(cxt)
if err != nil {
	if info, err := db.IsErrUniqueConstraint(); err != nil {
		// Fields exists for Postgres and SQLite
		log.Printf("unique constraint on the fields: %s", info.Fields)

		// you can also compare it with generated field names:
		if info.Fields[0] == db.User.Name.Field() {
			// do something
		}

		// For MySQL and MongoDB, use the constraint key
		log.Printf("unique constraint on the key: %s", info.Key)
	}
}
```

fix #213

### CODE REVIEW

**Comment by nettrino** [comment]
@steebchen is this OK to be merged? would help a lot with error handling

**Comment by steebchen** [comment]
@nettrino Actually it would be great if you could try it using 

```
go get github.com/steebchen/prisma-client-go@135de2bd282850bcc54e1604a56456ad8008a318
```

and re-generate the client. 

This PR includes some tests but it would be great for someone to actually use it and check if everything looks good. Thanks! Feel free to ping me in [discord](https://goprisma.org/docs/community) as well.

**Comment by ytsruh** [comment]
Tested on Postgres (Neon DB) tonight and it works fine for me. Unique constraints on both BigInt & String types work as expected. Thanks for this!

**Comment by nettrino** [comment]
@steebchen Has also been running fine for me for a week or so, so this should be good to merge!

**Comment by steebchen** [comment]
Awesome thanks! One thing which @abelanger5 mentioned is that it would be nice if `errors.As` would work, which it doesn't right now. It needs some refactor though and some extra work, so I'll just merge this as is and anything else can be an extra improvement.

**Pull request merged**
